[package]
name = "daqbuf-parse"
version = "0.0.3"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
humantime-serde = "1.1"
chrono = { version = "0.4.26", features = ["serde"] }
bytes = "1.10"
byteorder = "1.4"
hex = "0.4.3"
nom = "7.1.3"
autoerr = "0.0"
daqbuf-err = { path = "../daqbuf-err" }
netpod = { path = "../daqbuf-netpod", package = "daqbuf-netpod" }
