[workspace]
resolver = "3"
members = [
    "daqbuf-netpod",
    "daqbuf-err",
    "daqbuf-bitshuffle",
    "daqbuf-items-0",
    "daqbuf-items-proc",
    "daqbuf-parse",
    "daqbuf-items-2",
    "daqbuf-log",
    "daqbuf-series",
    "daqbuf-query",
    "daqbuf-serde-helper",
    "daqbuf-streams",
    "mettrics-macros",
]
