[package]
name = "daqbuf-batchtools"
version = "0.0.2"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2021"

[lib]
doctest = false

[dependencies]
log = { path = "../daqbuf-log", package = "daqbuf-log" }
err = { path = "../daqbuf-err", package = "daqbuf-err" }
taskrun = { path = "../daqbuf-taskrun", package = "daqbuf-taskrun" }
async-channel = "2.5.0"
futures = "0.3.31"
