[package]
name = "daqbuf-stats"
version = "0.0.2"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
edition = "2021"

[lib]
path = "src/stats.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
rand_xoshiro = "0.8.1"
stats_types = { path = "../daqbuf-stats_types", package = "daqbuf-stats_types" }
stats_proc = { path = "../daqbuf-stats_proc", package = "daqbuf-stats_proc" }
log = { path = "../daqbuf-log", package = "daqbuf-log" }
mettrics = { version = "0.0.7", path = "../mettrics" }
ca_proto = { path = "../daqbuf-ca-proto", package = "daqbuf-ca-proto" }
