use std::env;
use std::fs;
use std::io;
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;

fn mark_rerun_for_tree(root: &Path) -> io::Result<()> {
    println!("cargo:rerun-if-changed={}", root.display());
    for entry in fs::read_dir(root)? {
        let entry = entry?;
        let path = entry.path();
        println!("cargo:rerun-if-changed={}", path.display());
        if path.is_dir() {
            mark_rerun_for_tree(&path)?;
        }
    }
    Ok(())
}

fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_files(root, &path, out)?;
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/"); // normalize on Windows
            out.push((rel, path));
        }
    }
    Ok(())
}

fn guess_mime(path: &str) -> &'static str {
    match path
        .rsplit('.')
        .next()
        .map(|s| s.to_ascii_lowercase())
        .as_deref()
    {
        Some("html") | Some("htm") => "text/html; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("js") => "application/javascript; charset=utf-8",
        Some("mjs") => "text/javascript; charset=utf-8",
        Some("json") | Some("map") => "application/json; charset=utf-8",
        Some("svg") => "image/svg+xml; charset=utf-8",
        Some("txt") => "text/plain; charset=utf-8",
        Some("png") => "image/png",
        Some("jpg") | Some("jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        Some("ico") => "image/x-icon",
        Some("webp") => "image/webp",
        Some("wasm") => "application/wasm",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("ttf") => "font/ttf",
        Some("otf") => "font/otf",
        _ => "application/octet-stream",
    }
}

fn write_generated(assets: &[(String, PathBuf)]) -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let dest = out_dir.join("assets_generated.rs");
    let mut f = fs::File::create(&dest)?;
    writeln!(f, "// @generated by build.rs - DO NOT EDIT")?;
    writeln!(f, "#[allow(dead_code)]")?;
    writeln!(f, "pub const ALL_ASSET_PATHS: &[&str] = &[")?;
    for (rel, _) in assets {
        writeln!(f, "    {:?},", rel)?;
    }
    writeln!(f, "];")?;
    writeln!(f)?;
    // Export a function to fetch bytes + content-type by relative path
    writeln!(
        f,
        "pub fn get_asset(path: &str) -> Option<(&'static [u8], &'static str)> {{"
    )?;
    writeln!(f, "    let key = path.trim_start_matches('/');")?;
    writeln!(f, "    match key {{")?;
    for (rel, _p) in assets {
        let mime = guess_mime(rel);
        writeln!(
            f,
            "        {rel:?} => Some((include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/files/\", {rel:?})) as &'static [u8], {mime:?})),",
            rel = rel,
            mime = mime
        )?;
    }
    writeln!(f, "        _ => None,")?;
    writeln!(f, "    }}")?;
    writeln!(f, "}}")?;
    f.write(b"\n")?;
    writeln!(
        f,
        "pub fn all_asset_paths() -> &'static [&'static str] {{ ALL_ASSET_PATHS }}"
    )?;
    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    let files_dir = PathBuf::from(&manifest_dir).join("files");
    let mut assets = Vec::new();
    if !files_dir.exists() {
        if false {
            println!(
                "cargo:warning=No 'files' directory found at {}. Skipping embedding.",
                files_dir.display()
            );
            return Ok(());
        }
    } else {
        mark_rerun_for_tree(&files_dir)?;
        collect_files(&files_dir, &files_dir, &mut assets)?;
    }
    write_generated(&assets)?;
    Ok(())
}
