[package]
name = "daqbuf-serde-helper"
version = "0.0.1"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
license = "GPL-3.0-only"
edition = "2024"

[features]
default = ["derive"]
derive = ["dep:daqbuf-serde-helper-derive"]
schema = ["dep:utoipa"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
daqbuf-serde-helper-derive = { path = "../daqbuf-serde-helper-derive", optional = true }
utoipa = { version = "5", optional = true }
