[package]
name = "daqbuf-netfetch"
version = "0.0.3"
authors = ["Dominik Werder <dominik.werder@gmail.com>"]
license = "GPL-3.0-only"
edition = "2024"

[lib]
doctest = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11"
serde_yaml = "0.9.16"
ciborium = "0.2.2"
hcl-rs = "0.19.2"
tokio-stream = { version = "0.1", features = ["fs"] }
tokio-util = "0.7.18"
tracing = "0.1.37"
async-channel = "2.5.0"
crossfire = { version = "2.1.10", features = [] }
# crossfire = { version = "3.1.7", features = ["compat"] }
bytes = "1.10"
arrayref = "0.3"
byteorder = "1.5"
futures = "0.3.31"
md-5 = "0.10.5"
hex = "0.4.3"
regex = "1.11.2"
axum = "0.8.4"
http-body = "1"
tower-http = { version = "0.6.8", features = ["compression-gzip", "cors"] }
utoipa = { version = "5", features = ["axum_extras"] }
utoipa-axum = "0.2"
utoipa-swagger-ui = { version = "9", features = ["axum"] }
url = "2.5"
chrono = "0.4"
time = { version = "0.3.40", features = ["serde"] }
humantime = "2.1.0"
humantime-serde = "1.1.1"
pin-project = "1"
lazy_static = "1"
libc = "0.2"
slidebuf = "0.0.1"
dashmap = "6.1.0"
hashbrown = "0.16.0"
smallvec = "1.13.2"
autoerr = "0.0"
log = { path = "../daqbuf-log", package = "daqbuf-log" }
series = { path = "../daqbuf-series", package = "daqbuf-series" }
serieswriter = { path = "../daqbuf-serieswriter", package = "daqbuf-serieswriter" }
stats = { path = "../daqbuf-stats", package = "daqbuf-stats" }
scywr = { path = "../daqbuf-scywr", package = "daqbuf-scywr" }
dbpg = { path = "../daqbuf-dbpg", package = "daqbuf-dbpg" }
ingest-linux = { path = "../daqbuf-ingest-linux", package = "daqbuf-ingest-linux" }
err = { path = "../daqbuf-err", package = "daqbuf-err" }
netpod = { path = "../daqbuf-netpod", package = "daqbuf-netpod" }
items_0 = { path = "../daqbuf-items-0", package = "daqbuf-items-0" }
items_2 = { path = "../daqbuf-items-2", package = "daqbuf-items-2" }
streams = { path = "../daqbuf-streams", package = "daqbuf-streams" }
ca_proto = { path = "../daqbuf-ca-proto", package = "daqbuf-ca-proto" }
ca-proto-tokio = { path = "../daqbuf-ca-proto-tokio", package = "daqbuf-ca-proto-tokio" }
serde-helper = { path = "../daqbuf-serde-helper", package = "daqbuf-serde-helper" }
taskrun = { path = "../daqbuf-taskrun", package = "daqbuf-taskrun" }
mrucache = { path = "../daqbuf-mrucache", package = "daqbuf-mrucache" }
batchtools = { path = "../daqbuf-batchtools", package = "daqbuf-batchtools" }
daqingest-ui = { path = "../daqbuf-ingest-ui", package = "daqbuf-ingest-ui" }

[features]
disabled = []

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
